doctrine:
    dbal:
        connections:
            site_public_repository_connection:
                driver: pdo_mysql
                host: localhost
                user: ez
                password: eiHelppoo
                dbname: ezpublish_fi
                charset: UTF8
ezpublish:
    imagemagick:
        enabled: true
        path: /usr/bin/convert
    repositories:
        site_public_repository:
            engine: legacy
            connection: site_public_repository_connection
    siteaccess:
        default_siteaccess: site_admin
        list:
            - site_public
            - site_blog_public
            - site_admin
        groups:
            mainsites_group:
                - site_public
                - site_blog_public
                - site_admin
        match:
            URIElement: '1'
            Map\Host:
                ezpublish.fi.local: site_public
                blog.ezpublish.fi.local: site_blog_public
                admin.ezpublish.fi.local: site_admin
    system:
        mainsites_group:
            repository: site_public_repository
            var_dir: var/ezpublish_fi
            image_variations:
                reference:
                    reference: null
                    filters:
                        - { name: geometry/scaledownonly, params: [600, 600] }
                small:
                    reference: reference
                    filters:
                        - { name: geometry/scaledownonly, params: [100, 100] }
                tiny:
                    reference: reference
                    filters:
                        - { name: geometry/scaledownonly, params: [30, 30] }
                medium:
                    reference: reference
                    filters:
                        - { name: geometry/scaledownonly, params: [200, 200] }
                large:
                    reference: reference
                    filters:
                        - { name: geometry/scaledownonly, params: [300, 300] }
                rss:
                    reference: reference
                    filters:
                        - { name: geometry/scale, params: [88, 31] }
        site_public:
            legacy_mode: true
            languages:
                - eng-GB
        site_admin:
            legacy_mode: true
            languages:
                - eng-GB
                - fin-FI
        site_blog_public:
            languages:
                - eng-GB
                - fin-FI
stash:
    caches:
        default:
            drivers:
                - FileSystem
            inMemory: true
            registerDoctrineAdapter: false
